#ifndef SETTINGS_MODELS_H
#define SETTINGS_MODELS_H

#include "../macros_cblas.hpp"

#define PATH_MODELS "models"
#define BASE_FNAME "model_"
#define EXTENSION ".dat"

#define APPEND(PATH, BASE, NAME, EXT) PATH "/" BASE NAME EXT
#define COMPOSE(NAME) APPEND(PATH_MODELS, BASE_FNAME, NAME, EXTENSION)

/* MULTIPLICATION KERNELS' MODEL PATHS */
#define FNAME_GEMM COMPOSE(CG_GEMM)
#define FNAME_SYMM COMPOSE(CG_SYMM)
#define FNAME_TRMM COMPOSE(CG_TRMM)
#define FNAME_DIMM COMPOSE(CG_DIMM)
#define FNAME_SYSYMM COMPOSE(CG_SYSYMM)
#define FNAME_TRSYMM COMPOSE(CG_TRSYMM)
#define FNAME_DISYMM COMPOSE(CG_DISYMM)
#define FNAME_TRTRMM COMPOSE(CG_TRTRMM)
#define FNAME_DITRMM COMPOSE(CG_DITRMM)
#define FNAME_DIDIMM COMPOSE(CG_DIDIMM)

/* SYSTEM SOLVER KERNELS' MODEL PATHS */
#define FNAME_TRSM COMPOSE(CG_TRSM)
#define FNAME_DISV COMPOSE(CG_DISV)
#define FNAME_DIDISV COMPOSE(CG_DIDISV)
#define FNAME_DITRSV COMPOSE(CG_DITRSV)
#define FNAME_DISYSV COMPOSE(CG_DISYSV)
#define FNAME_GEGESV COMPOSE(CG_GEGESV)
#define FNAME_GESYSV COMPOSE(CG_GESYSV)
#define FNAME_GETRSV COMPOSE(CG_GETRSV)
#define FNAME_GEDISV COMPOSE(CG_GEDISV)
#define FNAME_TRSYSV COMPOSE(CG_TRSYSV)
#define FNAME_TRTRSV COMPOSE(CG_TRTRSV)
#define FNAME_TRDISV COMPOSE(CG_TRDISV)
#define FNAME_SYGESV COMPOSE(CG_SYGESV)
#define FNAME_SYSYSV COMPOSE(CG_SYSYSV)
#define FNAME_SYTRSV COMPOSE(CG_SYTRSV)
#define FNAME_SYDISV COMPOSE(CG_SYDISV)
#define FNAME_POGESV COMPOSE(CG_POGESV)
#define FNAME_POSYSV COMPOSE(CG_POSYSV)
#define FNAME_POTRSV COMPOSE(CG_POTRSV)
#define FNAME_PODISV COMPOSE(CG_PODISV)

#endif
